### ISSUE TITLE
compiler (version) as a parameter of kernel_generator

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/tuxml#22]
Right now, compilations are made with gcc version: 6.3.0-18+deb9u1 and libc version: 2.24-11+deb9u4
We would like to have the ability to change the compiler version (still with gcc, but might even be clang in the future)

in particular, we expect that for gcc version >= 9, the size of configuration kernel can change (we've made some ad-hoc experiments with tiny kernel showing this trend)

 - [x] add the parameter 
 - [x] handle the parameter in Python
 - [x] provide custom Docker files (and build images)
 - [x] send the right information to the database (wrt compiler version but also libc and so on) 
 - [x] tests on different configurations (eg with gcc 6.3 and gcc 9.0) and compare the sizes

**Comment by FabienZa** [comment]
Work in progress in branch :  
https://github.com/TuxML/tuxml/tree/issue-22-compiler-as-a-parameter

Almost done for gcc 7 and 8 : need somes tests for be sure, specially for the informations in database.

**Comment by FabienZa** [comment]
It seem than the version 9 of GCC is only in "test" or "unstable" for debian:stretch :  
https://tracker.debian.org/pkg/gcc-9

**Comment by FabienZa** [comment]
Version 7, 9 and 9 work when the argument --tiny is used.
But there are some errors for compile "normal" kernel.

**Comment by acherm** [comment]
nice work!
