### ISSUE TITLE
Support of other architectures (!= x86_64)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/tuxml#42]
Right now, we have focused on x86_64 architecture and we're usually presetting this option with randconfig
In fact there is an option called --seed that allows one to set specific pre-set options' values. 
On large scale experiments, we're doing something like this: 
`python3 kernel_generator.py --dev 200 --linux_version 5.8 --local --seed x86_64.config`

see https://github.com/TuxML/tuxml/blob/master/compilation/compiler.py#L213
https://github.com/TuxML/tuxml/blob/master/compilation/x64.config 
https://github.com/TuxML/tuxml/blob/master/compilation/settings.py#L15
(for tiny/randconfig)

what's a bit intuitive is that by default there is https://github.com/TuxML/tuxml/blob/master/compilation/tuxml.config that is systematically used (default seed). It was partlly used for 4.13.3 and 4.15 for preventing some bugs. It's a legacy we should remove. 

We need to:
 - [x] change the `tuxml.config` as the default seed
 - [x] I dislike the "seed" terminology, one needs another term like "preset"
 - [x] experiment different architectures (thus preset) such as `arm`. However it would certainly require cross-compilation support and so new Docker images (eg https://github.com/kernelci/kernelci-core/blob/main/jenkins/dockerfiles/gcc-8_arm/Dockerfile). I suggest to try experimenting with x86_32 (which is another closed architecture) and then others like `arm`

**Comment by acherm** [comment]
requires some experiments, but arch support is basically here now.
